Added CONTRIBUTING and CODE_OF_CONDUCT
NCSU-Group7-SE2021/Binge pull request #9
Opened 2021-09-24 04:09 UTC by kirantejatummuri

2021-09-24 04:54 UTC, isha-bansal0115 requested changes

2021-09-24 04:54 UTC, isha-bansal0115 commented on CONTRIBUTING.md
> +If for any reason you have questions on the process, feel free to reach us back at [igupta@ncsu.edu](mailto:ktummur@ncsu.edu). Github process can be very complex and we dont want to loose your valuab
in [], it has my email id and in () it has yours. Can you proof read this once?

2021-09-24 14:53 UTC, kirantejatummuri commented on CONTRIBUTING.md
> +If for any reason you have questions on the process, feel free to reach us back at [igupta@ncsu.edu](mailto:ktummur@ncsu.edu). Github process can be very complex and we dont want to loose your valuab
Changed it, thank you!

2021-09-24 22:40 UTC, rahulkalita8 commented
@isha-bansal0115 I did not review it. Does it look good to you. If yes, please let me know. I will merge

2021-09-25 23:47 UTC, isha-bansal0115 approved these changes
Looks good.

@kirantejatummuri your PR has conflicts. Please resolve and update so that we can merge

2021-09-25 23:48 UTC, isha-bansal0115 commented
@rahulkalita8  looks good. You can merge

2021-09-26 03:31 UTC, merged